// File generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes all Firebase options
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeNT050GKSY_q7_7RazpFrHgIo_IgU60M',
    appId: '1:192014714672:android:26910181757f6a9b3c6af5',
    messagingSenderId: '192014714672',
    projectId: 'studytask-tracker-bbfb3',
    storageBucket: 'studytask-tracker-bbfb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLV0jcV0LoIVNqdqAEajz7Tr0UjpYvTM',
    appId: '1:192014714672:ios:7bb18dfcba55a0233c6af5',
    messagingSenderId: '192014714672',
    projectId: 'studytask-tracker-bbfb3',
    storageBucket: 'studytask-tracker-bbfb3.firebasestorage.app',
    iosBundleId: 'com.example.studytaskTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLV0jcV0LoIVNqdqAEajz7Tr0UjpYvTM',
    appId: '1:192014714672:ios:7bb18dfcba55a0233c6af5',
    messagingSenderId: '192014714672',
    projectId: 'studytask-tracker-bbfb3',
    storageBucket: 'studytask-tracker-bbfb3.firebasestorage.app',
    iosBundleId: 'com.example.studytaskTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz85WiZNh5B3_jEpVMwVgjckXdz2Is5sg',
    appId: '1:192014714672:web:6c6d746bb836675a3c6af5',
    messagingSenderId: '192014714672',
    projectId: 'studytask-tracker-bbfb3',
    authDomain: 'studytask-tracker-bbfb3.firebaseapp.com',
    storageBucket: 'studytask-tracker-bbfb3.firebasestorage.app',
    measurementId: 'G-Q1BMHQVW2W',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz85WiZNh5B3_jEpVMwVgjckXdz2Is5sg',
    appId: '1:192014714672:web:159298ba0998dca73c6af5',
    messagingSenderId: '192014714672',
    projectId: 'studytask-tracker-bbfb3',
    authDomain: 'studytask-tracker-bbfb3.firebaseapp.com',
    storageBucket: 'studytask-tracker-bbfb3.firebasestorage.app',
    measurementId: 'G-ZEE1Y6ES0Q',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAp0_d_-HbbgyWsdhFHFy1O2m2ST6wrODI',
    appId: '1:145410987696:linux:placeholder',
    messagingSenderId: '145410987696',
    projectId: 'studytask-tracker',
    storageBucket: 'studytask-tracker.firebasestorage.app',
  );
}