// File generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes all Firebase options
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp0_d_-HbbgyWsdhFHFy1O2m2ST6wrODI',
    appId: '1:145410987696:android:16603d4f3d42de1cc90d75',
    messagingSenderId: '145410987696',
    projectId: 'studytask-tracker',
    storageBucket: 'studytask-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp0_d_-HbbgyWsdhFHFy1O2m2ST6wrODI',
    appId: '1:145410987696:ios:placeholder',
    messagingSenderId: '145410987696',
    projectId: 'studytask-tracker',
    storageBucket: 'studytask-tracker.firebasestorage.app',
    iosBundleId: 'com.example.studytaskTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp0_d_-HbbgyWsdhFHFy1O2m2ST6wrODI',
    appId: '1:145410987696:macos:placeholder',
    messagingSenderId: '145410987696',
    projectId: 'studytask-tracker',
    storageBucket: 'studytask-tracker.firebasestorage.app',
    iosBundleId: 'com.example.studytaskTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp0_d_-HbbgyWsdhFHFy1O2m2ST6wrODI',
    appId: '1:145410987696:windows:placeholder',
    messagingSenderId: '145410987696',
    projectId: 'studytask-tracker',
    storageBucket: 'studytask-tracker.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp0_d_-HbbgyWsdhFHFy1O2m2ST6wrODI',
    appId: '1:145410987696:web:placeholder',
    messagingSenderId: '145410987696',
    projectId: 'studytask-tracker',
    storageBucket: 'studytask-tracker.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAp0_d_-HbbgyWsdhFHFy1O2m2ST6wrODI',
    appId: '1:145410987696:linux:placeholder',
    messagingSenderId: '145410987696',
    projectId: 'studytask-tracker',
    storageBucket: 'studytask-tracker.firebasestorage.app',
  );
}
